version: '2'
services:
  web:
    image: hitalos/laravel:latest
    container_name: greatcv-web
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
    links:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: greatcv
      DB_USERNAME: greatcv
      DB_PASSWORD: greatcv
      DB_CONNECTION: pgsql
  db:
    image: postgres:9.4-alpine
    container_name: greatcv-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: greatcv
      POSTGRES_USER: greatcv
      POSTGRES_PASSWORD: greatcv
